/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.egyption_league;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author mmmme
 */
public class Team_Information_Enter extends javax.swing.JFrame {
    Connection   con;
    /**
     * Creates new form Team_Information_Enter
     */
    public Team_Information_Enter() {
        initComponents();
         
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Egyption_league_data", "root", "root");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "connection faild"); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        team_id_tf = new javax.swing.JTextField();
        team_name_tf = new javax.swing.JTextField();
        team_captin_tf = new javax.swing.JTextField();
        Add_B = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Team Name ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 310, 203, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Team id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 200, -1, 20));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Team Coach");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 420, -1, -1));

        team_id_tf.setBackground(new java.awt.Color(0, 0, 0));
        team_id_tf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        team_id_tf.setForeground(new java.awt.Color(255, 255, 255));
        team_id_tf.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(team_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 460, 40));

        team_name_tf.setBackground(new java.awt.Color(0, 0, 0));
        team_name_tf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        team_name_tf.setForeground(new java.awt.Color(255, 255, 255));
        team_name_tf.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(team_name_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 460, 40));

        team_captin_tf.setBackground(new java.awt.Color(0, 0, 0));
        team_captin_tf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        team_captin_tf.setForeground(new java.awt.Color(255, 255, 255));
        team_captin_tf.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(team_captin_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 460, 40));

        Add_B.setBackground(new java.awt.Color(0, 0, 0));
        Add_B.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Add_B.setForeground(new java.awt.Color(255, 255, 255));
        Add_B.setText("ADD");
        Add_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_bb(evt);
            }
        });
        jPanel1.add(Add_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 105, 38));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel5.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Egyptian League DATA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 56, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 120, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackagei/artboard_26.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 800, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Add_bb(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_bb
        
  
if(team_name_tf.getText().isEmpty()||team_id_tf.getText().isEmpty())
    JOptionPane.showMessageDialog(this, "Name And ID are Required ");
else{
        try {
            PreparedStatement stmt=con.prepareCall("insert into teams(name,id,captin)values(?,?,?); ");
            stmt.setString(1,team_name_tf.getText() );
            stmt.setInt(2, Integer.parseInt(team_id_tf.getText()));
           stmt.setString(3,team_captin_tf.getText() );
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Added successfully");   
        } catch (Exception e) {
 JOptionPane.showMessageDialog(this, "Duplicated Or Invalid Inputs ");        }
        }
        team_id_tf.setText(null);
       team_name_tf.setText(null);
        team_captin_tf.setText(null);
        
    }//GEN-LAST:event_Add_bb

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

       Teams s=new Teams();
        s.setVisible(true);
        s.setLocation(this.location());
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Team_Information_Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Team_Information_Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Team_Information_Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Team_Information_Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Team_Information_Enter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_B;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField team_captin_tf;
    private javax.swing.JTextField team_id_tf;
    private javax.swing.JTextField team_name_tf;
    // End of variables declaration//GEN-END:variables
}
