/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.egyption_league;


import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author mmmme
 */
public class update_team_info extends javax.swing.JFrame {
     Connection con;
    /**
     * Creates new form update_team_info
     */
    public update_team_info() {
        initComponents();
           try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Egyption_league_data", "root", "root");
              
        } catch (Exception e) {
 JOptionPane.showMessageDialog(this, "connection faild");        }
        fill_combo();
        fill_combo2();
        fill_combo3();
        fill_combo5();
        jComboBox1.disable();
         jComboBox2.disable();
       jComboBox4.disable();
        jButton1.setEnabled(false);
         jButton2.setEnabled(false);
         jTextField4.setEnabled(false);
         jTextField4.setForeground(Color.gray);

       jTextField4.setFont(new Font("TimesRoman", 12,12)   );
         
    }
    
    public void fill_combo(){
    
      try {
       
         PreparedStatement stmt=con.prepareStatement("Select name from teams" );
         ResultSet rs=stmt.executeQuery();
         while(rs.next()){
         jComboBox1.addItem(rs.getString(1));
         
         }
        
    } catch (Exception e) {}}
    public void fill_combo5(){
    
      try {
       
         PreparedStatement stmt=con.prepareStatement("Select name from teams" );
         ResultSet rs=stmt.executeQuery();
         while(rs.next()){
         jComboBox5.addItem(rs.getString(1));
         
         }
        
    } catch (Exception e) {}}
     public void  fill_combo3(){
    
      try {
       
         PreparedStatement stmt=con.prepareStatement("Select name from teams" );
         ResultSet rs=stmt.executeQuery();
         while(rs.next()){
             
         jComboBox3.addItem(rs.getString(1));
         
         }
        
    } catch (Exception e) {
    }
    
    
    }
    public void fill_combo2(){
    
       try {
       
         PreparedStatement stmt=con.prepareStatement("Select name from Players" );
         ResultSet rs=stmt.executeQuery();
         while(rs.next()){
         jComboBox2.addItem(rs.getString(1));
         
         }
        
    } catch (Exception e) {
    }

    
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Team Coach");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("BACK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To Team");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New  Player");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 187, -1));

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 190, 35));
        jTextField4.getAccessibleContext().setAccessibleName("");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("UPDATE PLAYER");
        jButton1.setDoubleBuffered(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 143, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT TEAM" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 310, 35));
        jComboBox1.getAccessibleContext().setAccessibleName("");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From Team");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 187, -1));

        jComboBox3.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT TEAM" }));
        jComboBox3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox3FocusGained(evt);
            }
        });
        jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 310, 35));
        jComboBox3.getAccessibleContext().setAccessibleName("");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New  Player Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox4PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 310, 35));
        jComboBox4.getAccessibleContext().setAccessibleName("");

        jComboBox2.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 310, 35));
        jComboBox2.getAccessibleContext().setAccessibleName("");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New Team For Coach");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jComboBox5.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT TEAM" }));
        jComboBox5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox5FocusGained(evt);
            }
        });
        jComboBox5.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox5PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 188, 35));
        jComboBox5.getAccessibleContext().setAccessibleName("");

        jSeparator1.setBackground(new java.awt.Color(0, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 596, 20));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE COACH");
        jButton2.setFocusCycleRoot(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 143, -1));

        jLabel8.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Egyptian League DATA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackagei/artboard_26.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Teams s= new Teams();
        s.setVisible(true);
        s.setLocation(this.location());
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
      jComboBox1.removeAllItems();
        try {
           PreparedStatement stmt=con.prepareStatement("Select name from teams" );
         ResultSet rs=stmt.executeQuery();
         while(rs.next()){
        if(!rs.getString(1).equals(jComboBox3.getSelectedItem().toString()))
         jComboBox1.addItem(rs.getString(1)); 
                  
         }
                
              
        } catch (Exception e) {
 JOptionPane.showMessageDialog(this, "connection faild");        }    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox3PopupMenuWillBecomeInvisible
    
       jComboBox2.removeAllItems();
        try {
               PreparedStatement stmt=con.prepareStatement("Select name from players where team_name=?" );
                stmt.setString(1, jComboBox3.getSelectedItem().toString());
         ResultSet rs=stmt.executeQuery();
         
         while(rs.next()){
        
         jComboBox2.addItem(rs.getString("name")); }
                 
              
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "connection faild"); 
        }
    }//GEN-LAST:event_jComboBox3PopupMenuWillBecomeInvisible

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        try {
                PreparedStatement stmt=con.prepareStatement("Select name from players where team_name=?" );
                stmt.setString(1, jComboBox3.getSelectedItem().toString());
         ResultSet rs=stmt.executeQuery();
         jComboBox2.removeAllItems();
         while(rs.next()){
        
         jComboBox2.addItem(rs.getString("name")); }
                  
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "connection faild"); 
        }
        
        
        try {
            
             
            jComboBox4.removeAllItems();
           
              
                PreparedStatement  stmt=con.prepareStatement("select number from players where team_name=?");
                  stmt.setString(1, jComboBox1.getSelectedItem().toString());
                ResultSet  rs=stmt.executeQuery();
                  
                  for (int i = 1; i < 100; i++) {
                      
                jComboBox4.addItem(String.valueOf(i));
            }
                  while(rs.next()){
                  jComboBox4.removeItem(String.valueOf(rs.getInt(1)));
                  
                  }
                  
                   jComboBox2.enable();
                  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "kdfjgjrfd");
        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
 
        
        jTextField4.setText(null);
       jTextField4.setForeground(Color.white);
       jTextField4.setFont(new Font("Segoe ui", 12, 18)   );
       
       
       jButton2.setEnabled(true);
     
           }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
jTextField4.setForeground(Color.gray);

       jTextField4.setFont(new Font("Italic ",12,12)   );
       
     }//GEN-LAST:event_jTextField4FocusLost

    private void jComboBox3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox3FocusGained
jComboBox3.removeAllItems();
        try {
           PreparedStatement stmt=con.prepareStatement("Select name from teams" );
         ResultSet rs=stmt.executeQuery();
         while(rs.next()){
        if(!rs.getString(1).equals(jComboBox1.getSelectedItem().toString()))
         jComboBox3.addItem(rs.getString(1)); 
                  
         }
               jComboBox1.enable();    
                  
                  

        } catch (Exception e) {
 JOptionPane.showMessageDialog(this, "connection faild");        }     }//GEN-LAST:event_jComboBox3FocusGained

    private void jComboBox5PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox5PopupMenuWillBecomeInvisible
     jTextField4.setText(null);
        try {
              PreparedStatement  stmt=con.prepareStatement("Select captin from teams where name=?" );
                  stmt.setString(1, jComboBox5.getSelectedItem().toString());
                  ResultSet   rs=stmt.executeQuery();
                  
                  while(rs.next()){
                  jTextField4.setText("current coach is "+rs.getString(1));
                  
                  
                  }
                  
        } catch (Exception e) {
        }
        jTextField4.enable();
    }//GEN-LAST:event_jComboBox5PopupMenuWillBecomeInvisible

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        try {int f1=1;
        
           if(jTextField4.getText().startsWith("current")||jTextField4.getText().isEmpty())
                        JOptionPane.showMessageDialog(this, "Empty Field  !!!!!!!!!!!....Enter Coach Name");
         else  {
           if(!jTextField4.getText().isEmpty())
           {
                PreparedStatement stmt=con.prepareStatement("select captin from teams where name=?");
                stmt.setString(1, jComboBox5.getSelectedItem().toString());
               ResultSet rs=stmt.executeQuery();
                rs.next();
                if(rs.getString(1).equalsIgnoreCase(jTextField4.getText()))
                 JOptionPane.showMessageDialog(this, "Already The Coach!!!!");
                else
                {
                    stmt=con.prepareStatement("select captin from teams");
                    rs=stmt.executeQuery();
                    while(rs.next()){
                        if(rs.getString(1).equals(jTextField4.getText())){
                          stmt=con.prepareStatement("update teams set captin=? where captin=?");
                        stmt.setString(1, "");
                        stmt.setString(2, jTextField4.getText());
                        stmt.executeUpdate();
                        break;}
                    }stmt=con.prepareStatement("select captin from teams where name=?");
                    stmt.setString(1,  jComboBox5.getSelectedItem().toString());
                    ResultSet rss=stmt.executeQuery();
                    rss.next();
                    stmt=con.prepareStatement("update teams set captin=? where name=?");
                    stmt.setString(1, jTextField4.getText());
                    stmt.setString(2, jComboBox5.getSelectedItem().toString());
                  f1=   JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Kick    \""+rss.getString(1)+"\"   Out And Hire  \""+jTextField4.getText()+"\" ???!!", "warning", JOptionPane.YES_NO_CANCEL_OPTION);
                  if(f1==0){ 
                  stmt.executeUpdate();
                     
                    JOptionPane.showMessageDialog(this, "Updated  Team Coach Successfully");
                  }




                }
               
           }
           }
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "Empty field");
            
        }
        
      
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {int f1=1;

            PreparedStatement stmt;

            stmt=con.prepareStatement("update players set number=?, team_name=? where name=?");
             f1= JOptionPane.showConfirmDialog(this,"\""+ jComboBox2.getSelectedItem().toString()+"\"    Will move To     \""+jComboBox1.getSelectedItem().toString()+"\"    Press Yes To Confirm", "Warning", JOptionPane.YES_NO_CANCEL_OPTION);
            if(f1==0){
             stmt.setString(2, jComboBox1.getSelectedItem().toString());
            
            stmt.setInt(1,Integer.parseInt(jComboBox4.getSelectedItem().toString()));
            stmt.setString(3, jComboBox2.getSelectedItem().toString());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Congratulations...New Player Added");}

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error");

        }

      

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
  jComboBox4.enable();    
                    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    private void jComboBox4PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox4PopupMenuWillBecomeInvisible
jButton1.setEnabled(true);


    }//GEN-LAST:event_jComboBox4PopupMenuWillBecomeInvisible

    private void jComboBox5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox5FocusGained
        jTextField4.setEnabled(true);
        jComboBox5.removeItem("SELECT TEAM");
    }//GEN-LAST:event_jComboBox5FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_team_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_team_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_team_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_team_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_team_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
