/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.egyption_league;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mmmme
 */
public class update_a_match extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form update_a_match
     */
    public update_a_match() {
        
        initComponents();
            try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Egyption_league_data", "root", "root");
        } catch (Exception e) {
 JOptionPane.showMessageDialog(this, "connection faild");        }
            
    fill_combo_1();
        fill_combo_2();
        fill_combo_3();
        jButton1.setEnabled(false);
    }
    
    
    
    public void fill_combo_1(){
      try {
        PreparedStatement stmt=con.prepareStatement("select id from matches where score=' -'");
        ResultSet rs=stmt.executeQuery();
        while(rs.next()){
        jComboBox1.addItem(rs.getString(1));
        
        }
    } catch (Exception e) {
    }
 }
  public void fill_combo_2(){
      try {
        PreparedStatement stmt=con.prepareStatement("select name from referees");
        ResultSet rs=stmt.executeQuery();
        while(rs.next()){
        jComboBox2.addItem(rs.getString(1));
        
        }
    } catch (Exception e) {
    }
 }
 public void fill_combo_3(){
      try {
        PreparedStatement stmt=con.prepareStatement("select name from stadiums");
        ResultSet rs=stmt.executeQuery();
        while(rs.next()){
        jComboBox3.addItem(rs.getString(1));
        
        }
    } catch (Exception e) {
    }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 42, 87));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 718));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Match ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 420, 32));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, -1, 32));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Match Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New Match Referee");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New Match Stadium");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, 43));

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner3.setToolTipText("");
        jSpinner3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, 43));

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 126, 43));

        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 126, 43));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter Match Score");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 409, 32));

        jComboBox3.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 410, 32));

        jComboBox4.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 113, 32));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jSpinner2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 87, 31));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        jSpinner1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 87, 31));

        jLabel9.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Egyptian League DATA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackagei/artboard_26.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        matches_frame s=new matches_frame();
        s.setVisible(true);
        s.setLocation(this.location());
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        boolean x=false;
       boolean y=false;
       boolean f=true;
       int count=0;
       PreparedStatement stmt;
        try { stmt=con.prepareStatement("select * from matches where id=?");
        stmt.setInt(1, Integer.parseInt(jComboBox1.getSelectedItem().toString()));
            ResultSet rss=stmt.executeQuery();
            rss.next();
            stmt=con.prepareStatement("select referee,team1,team2,stadium_name from matches where date=?");
        stmt.setString(1, jSpinner1.getValue().toString()+"-"+jSpinner2.getValue().toString()+"-"+jComboBox4.getSelectedItem().toString() );
            ResultSet rs=stmt.executeQuery();
            while(rs.next()){
              if(!rss.getString("date").equals(jSpinner1.getValue().toString()+"-"+jSpinner2.getValue().toString()+"-"+jComboBox4.getSelectedItem().toString())&&(jTextField6.getText().equals(rs.getString(3))||jTextField4.getText().equals(rs.getString(2))||jTextField6.getText().equals(rs.getString(2))||jTextField4.getText().equals(rs.getString(3))))
                     x=true;
                
                 if(jComboBox2.getSelectedItem().toString().equals(rs.getString(1))&& !rss.getString("referee").equals(jComboBox2.getSelectedItem().toString())  )
                     y=true;
                 if(jComboBox3.getSelectedItem().toString().equals(rs.getString("stadium_name"))&&!jComboBox3.getSelectedItem().toString().equals(rss.getString("stadium_name")))
                     count++;
                 if(jComboBox3.getSelectedItem().toString().equals(rss.getString("stadium_name"))&&!(jSpinner1.getValue().toString()+"-"+jSpinner2.getValue().toString()+"-"+jComboBox4.getSelectedItem().toString()).equals(rss.getString("date")))
                     count++;
                 if(rss.getString("referee").equals(jComboBox2.getSelectedItem().toString())&& !(jSpinner1.getValue().toString()+"-"+jSpinner2.getValue().toString()+"-"+jComboBox4.getSelectedItem().toString()).equals(rss.getString("date")))
                     {if(jComboBox2.getSelectedItem().toString().equals(rs.getString(1)))
                     y=true;
                     
                     }
                     }
            
            
            
               if(!rss.getString(4).equals(" -")){
       f=false;
        JOptionPane.showMessageDialog(this, "Match Alredy Has Score");
       }
               else
               {
            if(x)
               JOptionPane.showMessageDialog(this, "The Same Team Can't Play In The Same Day");
           
           if(y)         
              JOptionPane.showMessageDialog(this, "The Same Referee Can't Take More Than One Match In A Day");
       if(count>=2)
            JOptionPane.showMessageDialog(this, "The Same stadium Can't host More Than two Matchs In A Day");
       
    
           
            if(!x&&f&&!y&&count<2){
               
            stmt=con.prepareStatement("update matches set date=?,referee=?,score=?,stadium_name=? where id=?");
        stmt.setString(1, jSpinner1.getValue().toString()+"-"+jSpinner2.getValue().toString()+"-"+jComboBox4.getSelectedItem().toString() );
            stmt.setString(2, jComboBox2.getSelectedItem().toString());
            stmt.setString(3, jSpinner3.getValue().toString()+"-"+jSpinner4.getValue().toString());
            stmt.setString(4, jComboBox3.getSelectedItem().toString());
            stmt.setString(5, jComboBox1.getSelectedItem().toString());
            stmt.executeUpdate();
            
            
            stmt=con.prepareStatement("select total_score,p,w,L,D,GF,GA,GD,clsh from teams where name=? ");
            stmt.setString(1, jTextField6.getText());
            rs=stmt.executeQuery();
            rs.next();
            stmt=con.prepareStatement("select total_score,p,w,L,D,GF,GA,GD,clsh from teams where name=? ");
            stmt.setString(1, jTextField4.getText());
            rss=stmt.executeQuery();
            rss.next();
            stmt=con.prepareStatement("update  teams set total_score=?,p=?,w=?,L=?,D=?,GF=?,GA=?,GD=?,clsh=? where name=?; ");
            if(Integer.parseInt(jSpinner3.getValue().toString())>Integer.parseInt(jSpinner4.getValue().toString())){
            stmt.setInt(1,rs.getInt(1)+3 );
            stmt.setInt(2,rs.getInt(2)+1 );
            stmt.setInt(3, rs.getInt(3)+1);
            stmt.setInt(4,rs.getInt(4)+0 );
            stmt.setInt(5, rs.getInt(5)+0);
            stmt.setInt(6, rs.getInt(6)+(int)jSpinner3.getValue());
             stmt.setInt(7, rs.getInt(7)+(int)jSpinner4.getValue());
              stmt.setInt(8, rs.getInt(8)+((int)jSpinner3.getValue()-(int)jSpinner4.getValue()));
              if((int)jSpinner4.getValue()==0)
                  stmt.setInt(9, rs.getInt(9)+1);
              else
                   stmt.setInt(9, rs.getInt(9)+0);
            stmt.setString(10,jTextField6.getText());
            stmt.executeUpdate();
            stmt.setInt(1,rss.getInt(1)+0 );
            stmt.setInt(2,rss.getInt(2)+1 );
            stmt.setInt(3,rss.getInt(3)+0);
            stmt.setInt(4,rss.getInt(4)+1 );
            stmt.setInt(5, rss.getInt(5)+0);
            stmt.setInt(6, rss.getInt(6)+(int)jSpinner4.getValue());
             stmt.setInt(7, rss.getInt(7)+(int)jSpinner3.getValue());
                stmt.setInt(9, rss.getInt(9)+0);
              stmt.setInt(8, rss.getInt(8)+((int)jSpinner4.getValue()-(int)jSpinner3.getValue()));
            stmt.setString(10,jTextField4.getText());
            
            stmt.executeUpdate();
            
            
            }
            else if(Integer.parseInt(jSpinner3.getValue().toString())<Integer.parseInt(jSpinner4.getValue().toString())){
            stmt.setInt(1,rss.getInt(1)+3 );
            stmt.setInt(2,rss.getInt(2)+1 );
            stmt.setInt(3,rss.getInt(3)+1);
            stmt.setInt(4,rss.getInt(4)+0 );
            stmt.setInt(5, rss.getInt(5)+0);
             stmt.setInt(6, rss.getInt(6)+(int)jSpinner4.getValue());
             stmt.setInt(7, rss.getInt(7)+(int)jSpinner3.getValue());
              stmt.setInt(8, rss.getInt(8)+((int)jSpinner4.getValue()-(int)jSpinner3.getValue()));
              if((int)jSpinner3.getValue()==0)
                  stmt.setInt(9, rss.getInt(9)+1);
              else
                   stmt.setInt(9, rss.getInt(9)+0);
            stmt.setString(10,jTextField4.getText());
            stmt.executeUpdate();
            stmt.setInt(1,rs.getInt(1)+0 );
            stmt.setInt(2,rs.getInt(2)+1 );
            stmt.setInt(3, rs.getInt(3)+0);
            stmt.setInt(4,rs.getInt(4)+1 );
            stmt.setInt(5, rs.getInt(5)+0);
             stmt.setInt(6, rs.getInt(6)+(int)jSpinner3.getValue());
             stmt.setInt(7, rs.getInt(7)+(int)jSpinner4.getValue());
              stmt.setInt(8, rs.getInt(8)+((int)jSpinner3.getValue()-(int)jSpinner4.getValue()));
               stmt.setInt(9, rs.getInt(9)+0);
            stmt.setString(10,jTextField6.getText());
             stmt.executeUpdate();
            }
            else {
           stmt.setInt(1,rs.getInt(1)+1 );
            stmt.setInt(2,rs.getInt(2)+1 );
            stmt.setInt(3, rs.getInt(3)+0);
            stmt.setInt(4,rs.getInt(4)+0 );
            stmt.setInt(5, rs.getInt(5)+1);
             stmt.setInt(6, rs.getInt(6)+(int)jSpinner3.getValue());
             stmt.setInt(7, rs.getInt(7)+(int)jSpinner4.getValue());
             stmt.setInt(8, rs.getInt(8)+((int)jSpinner3.getValue()-(int)jSpinner4.getValue()));
             if((int)jSpinner4.getValue()==0)
                  stmt.setInt(9, rs.getInt(9)+1);
              else
                   stmt.setInt(9, rs.getInt(9)+0);
             
            stmt.setString(10,jTextField6.getText());
            stmt.executeUpdate();
              stmt.setInt(1,rss.getInt(1)+1 );
            stmt.setInt(2,rss.getInt(2)+1 );
            stmt.setInt(3,rss.getInt(3)+0);
            stmt.setInt(4,rss.getInt(4)+0 );
            stmt.setInt(5, rss.getInt(5)+1);
             stmt.setInt(6, rss.getInt(6)+(int)jSpinner4.getValue());
             stmt.setInt(7, rss.getInt(7)+(int)jSpinner3.getValue());
              stmt.setInt(8, rss.getInt(8)+((int)jSpinner4.getValue()-(int)jSpinner3.getValue()));
            if((int)jSpinner3.getValue()==0)
                  stmt.setInt(9, rss.getInt(9)+1);
              else
                   stmt.setInt(9, rss.getInt(9)+0);
            stmt.setString(10,jTextField4.getText());
             stmt.executeUpdate();}
            
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            
            
            
            
            
            }
               }
               
               jSpinner3.setValue(0);
                jSpinner4.setValue(0);
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "error");
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        try {
            PreparedStatement stmt=con.prepareStatement("select * from matches where id=?");
            stmt.setInt(1, Integer.parseInt(jComboBox1.getSelectedItem().toString()));
            ResultSet rs=stmt.executeQuery();
            rs.next();
            if(rs.getString("date").charAt(1)=='-')
            jSpinner1.setValue(Character.getNumericValue(rs.getString("date").charAt(0)));
            else
            jSpinner1.setValue(Integer.parseInt(String.valueOf(rs.getString("date").charAt(0))+String.valueOf(rs.getString("date").charAt(1))));
            if(rs.getString("date").charAt(1)=='-'&&rs.getString("date").length()==9)
       jSpinner2.setValue(Integer.parseInt(String.valueOf(rs.getString("date").charAt(2))+String.valueOf(rs.getString("date").charAt(3))));
       if(rs.getString("date").charAt(1)=='-'&&rs.getString("date").length()==8)
        jSpinner2.setValue(Integer.parseInt(String.valueOf(rs.getString("date").charAt(2))));
        if(rs.getString("date").charAt(2)=='-'&&rs.getString("date").length()==9)
        jSpinner2.setValue(Integer.parseInt(String.valueOf(rs.getString("date").charAt(3))));
        if(rs.getString("date").charAt(2)=='-'&&rs.getString("date").length()==10)
       jSpinner2.setValue(Integer.parseInt(String.valueOf(rs.getString("date").charAt(3))+String.valueOf(rs.getString("date").charAt(4))));

  
            jComboBox4.setSelectedItem(rs.getString("date").charAt(rs.getString("date").length()-4)+""+rs.getString("date").charAt(rs.getString("date").length()-3)+""+rs.getString("date").charAt(rs.getString("date").length()-2)+""+rs.getString("date").charAt(rs.getString("date").length()-1));
            System.out.println();
            jTextField6.setText(rs.getString("team1"));
            jTextField4.setText(rs.getString("team2"));
            jComboBox2.setSelectedItem(rs.getString("referee"));
            jComboBox3.setSelectedItem(rs.getString("stadium_name"));
            jButton1.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "connection faild");
        }

    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_a_match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_a_match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_a_match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_a_match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_a_match().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
