/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.egyption_league;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author mmmme
 */
public class update_player extends javax.swing.JFrame {
    Connection con;
    
       
        
                           

    /**
     * Creates new form update_player
     */
    public update_player() {
        initComponents();
       
         try {
    
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Egyption_league_data", "root", "root");
           
            	  fill_combo1();
            fill_combo2();
        
        } catch (Exception e) {
       JOptionPane.showMessageDialog(this, "Connection Faild");        }
        jComboBox4.disable();
         
                  jButton1.setEnabled(false);
                     jComboBox2.disable();
                  jSpinner1.disable();
                  jSpinner2.disable();
                  jComboBox1.disable();
         
         
         
        
    }
   public void fill_combo2(){
           try {
           
              PreparedStatement stmt=con.prepareCall("select name from players;  ");
            	  ResultSet rs=stmt.executeQuery();
            
                  while(rs.next())
                  {
                  jComboBox3.addItem(rs.getString(1));
                  
        }
        }
           catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Connection Faild");
                }
   }
  public void fill_combo1(){
           try {
           
              PreparedStatement stmt=con.prepareCall("select name from teams;  ");
            	  ResultSet rs=stmt.executeQuery();
            
                  while(rs.next())
                  {
                  jComboBox2.addItem(rs.getString(1));
                  
        }
        }
           catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Connection Faild");
                }
   }  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(13, 39, 87));
        jPanel1.setPreferredSize(new java.awt.Dimension(695, 711));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Player Position");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Update Player Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Update Player Age");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 370, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ubdate Player Score");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 440, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Update Player Team");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 510, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Forward", "Midfielder", "Defender", "Goalkeeper" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 400, 40));

        jComboBox2.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 400, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 85, 33));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Player name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, 203, -1));

        jComboBox3.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 400, 40));

        jComboBox4.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 400, 40));

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        jSpinner1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 400, 40));

        jSpinner2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 400, 40));

        jLabel9.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Egyptian League DATA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 53, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackagei/artboard_26.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 690, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Players_frame s=new Players_frame();
        s.setVisible(true);
        s.setLocation(this.location());
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
       int f1=1;
       int f2=1;
       int f3=1;
            
        try { 
           
            
            
           
               PreparedStatement  stmt=con.prepareStatement("select * from players where name=?");
                stmt.setString(1, jComboBox3.getSelectedItem().toString());
                ResultSet rss=stmt.executeQuery();
                rss.next();
                
              
                
               
                
                if(!(rss.getString(7).equalsIgnoreCase(jComboBox2.getSelectedItem().toString())))
                    JOptionPane.showMessageDialog(this, "Player Team Updated Successfully");
                
                if(rss.getInt("number")!=Integer.parseInt(jComboBox4.getSelectedItem().toString()))
                JOptionPane.showMessageDialog(this, "Player Number Updated Successfully");
               
                
                
                
    stmt=con.prepareStatement("update players set team_name=?,number=? where name=?");
            
            stmt.setString(1, jComboBox2.getSelectedItem().toString());
            stmt.setString(2, jComboBox4.getSelectedItem().toString());
            stmt.setString(3, jComboBox3.getSelectedItem().toString());
            stmt.executeUpdate();
            
             if(!(rss.getString(3).equalsIgnoreCase(jComboBox1.getSelectedItem().toString())))
                  f3=  JOptionPane.showConfirmDialog(this, "Are You Sure?!Player Poaition Will Change", "warning", JOptionPane.YES_NO_CANCEL_OPTION);
           if(f3==0)
           { stmt=con.prepareStatement("update players set position=? where name=?");
           stmt.setString(1, jComboBox1.getSelectedItem().toString());
           stmt.setString(2, jComboBox3.getSelectedItem().toString());
           stmt.executeUpdate();
           JOptionPane.showMessageDialog(this, "Player Position Updated Successfully");
           }
            
           
            if((int)jSpinner1.getValue()<rss.getInt("age"))
               f1= JOptionPane.showConfirmDialog(this, "Less Age,Are You Sure", "Warning", JOptionPane.YES_NO_CANCEL_OPTION);
               else if ((int)jSpinner1.getValue()>rss.getInt("age"))
               f1=0;
            
            if(f1==0)
            {
            stmt=con.prepareStatement("update players set age=? where name=?");
            stmt.setInt(1, (int)jSpinner1.getValue());
            stmt.setString(2, jComboBox3.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Age Updated Successflly");
            stmt.executeUpdate();}
             
            
            
            
           if((int)jSpinner2.getValue()<rss.getInt("score"))
            f2= JOptionPane.showConfirmDialog(this, "Less Score,Are You Sure", "Warning", JOptionPane.YES_NO_CANCEL_OPTION);
           else if ((int)jSpinner2.getValue()>rss.getInt("score"))
               f2=0;
            if(f2==0)
            {
            stmt=con.prepareStatement("update players set score=? where name=?");
            stmt.setInt(1, (int)jSpinner2.getValue());
            stmt.setString(2, jComboBox3.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Score Updated Successflly");
            stmt.executeUpdate();
               
            
            //Players_Rank_sort
            
             stmt=con.prepareStatement("select score from players");
           ResultSet rs=stmt.executeQuery();
        
            ArrayList <Integer> l=new ArrayList();
        while(rs.next()){
        l.add(rs.getInt(1));
        }
         Collections.sort(l, Collections.reverseOrder()); 
            
         stmt=con.prepareStatement("update players set ranke=? where score=?");
         stmt.setInt(1, 1);
                stmt.setInt(2, l.get(0));
                stmt.executeUpdate();
                int x1=1;
            for (int i = 1; i <l.size() ; i++) {
                stmt=con.prepareStatement("update players set ranke=? where score=?");
                
                        if(l.get(i-1)==l.get(i)){
                stmt.setInt(1, x1);
                stmt.setInt(2, l.get(i));
                        stmt.executeUpdate();
                                               }
                 else
                        {  x1++;
                                stmt.setInt(1, x1);
                stmt.setInt(2, l.get(i));
                stmt.executeUpdate();
                        }
                        
                        
            
            
            
            }
            
            }
           
            
            
           
            
        
            
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid inputs");
        }
        
        
        
      
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox3PopupMenuWillBecomeInvisible
try {jComboBox4.removeAllItems();
             PreparedStatement stmt=con.prepareStatement("select * from players where name=?;  ");
             stmt.setString(1, jComboBox3.getSelectedItem().toString());
            	  ResultSet rss=stmt.executeQuery();
                  rss.next();
                  jComboBox2.setSelectedItem(rss.getString("team_name"));
                  jSpinner1.setValue((rss.getInt("age")));
                  jSpinner2.setValue((rss.getInt("score")));
                  jComboBox1.setSelectedItem(rss.getString("position"));
                      stmt=con.prepareStatement("select number from players where team_name=?;  ");
                  stmt.setString(1, rss.getString("team_name"));
                  ResultSet rs=stmt.executeQuery();
                  for (int i = 1; i < 100; i++) {
                     
       jComboBox4.addItem(String.valueOf(i));
    }
                  while(rs.next()){
                      if(rs.getInt("number")==rss.getInt("number")&&jComboBox2.getSelectedItem().toString().equals(rss.getString("team_name")))
                          continue;
                    jComboBox4.removeItem(rs.getString("number"));
                  
                  }
                  if(jComboBox2.getSelectedItem().toString().equals(rss.getString("team_name")))
                  jComboBox4.setSelectedItem(String.valueOf(rss.getInt("number")));
                  else
                      jComboBox4.setSelectedItem(null);
                  jButton1.setEnabled(true);
                     jComboBox2.enable();
                  jSpinner1.enable();
                  jSpinner2.enable();
                  jComboBox1.enable();
                  jComboBox4.enable();
        }
           catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Connection Faild");
                }

    }//GEN-LAST:event_jComboBox3PopupMenuWillBecomeInvisible

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
       
       jComboBox4.removeAllItems();
        try {  PreparedStatement stmt=con.prepareStatement("select * from players where name=?;  ");
             stmt.setString(1, jComboBox3.getSelectedItem().toString());
            	  ResultSet rss=stmt.executeQuery();
                  rss.next();
                    stmt=con.prepareStatement("select number from players where team_name=?;  ");
                  stmt.setString(1, jComboBox2.getSelectedItem().toString());
                  ResultSet rs=stmt.executeQuery();
                  for (int i = 1; i < 100; i++) {
                     
       jComboBox4.addItem(String.valueOf(i));
    }
                  while(rs.next()){
                      if(rs.getInt("number")==rss.getInt("number")&&jComboBox2.getSelectedItem().toString().equals(rss.getString("team_name")))
                          continue;
                    jComboBox4.removeItem(rs.getString("number"));
                  
                  }
                  if(jComboBox2.getSelectedItem().toString().equals(rss.getString("team_name")))
                  jComboBox4.setSelectedItem(String.valueOf(rss.getInt("number")));
                  
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_player().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
}
